---
- name: Enable dark mode
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleInterfaceStyle
    type: string
    value: Dark
    state: present
  when: macos_dark_mode | bool

- name: Show all file extensions
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
    state: present
  when: macos_show_all_extensions | bool

- name: Expand save panel by default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true
    state: present
  when: macos_expand_save_panel | bool

- name: Expand print panel by default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: true
    state: present

- name: Disable "Are you sure you want to open this application?" dialog
  community.general.osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false
    state: present
  when: macos_disable_quarantine_dialog | default(true) | bool

- name: Disable auto-correct
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
    state: present
  when: macos_disable_autocorrect | default(true) | bool
