---
- name: Show hidden files in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    state: present
  notify: Restart Finder

- name: Show path bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
    state: present
  notify: Restart Finder

- name: Show status bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
    state: present
  notify: Restart Finder
