---
- name: Disable press-and-hold for keys in favor of key repeat
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: "{{ not macos_enable_key_repeat }}"
    state: present

- name: Set key repeat rate
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: "{{ macos_key_repeat_rate }}"
    state: present

- name: Set initial key repeat delay
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: "{{ macos_initial_key_repeat }}"
    state: present
