---
- name: Show date in menu bar clock
  community.general.osx_defaults:
    domain: com.apple.menuextra.clock
    key: ShowDate
    type: int
    value: "{{ 1 if macos_menubar_clock_show_date else 0 }}"
    state: present
  notify: Restart SystemUIServer

- name: Show day of week in menu bar clock
  community.general.osx_defaults:
    domain: com.apple.menuextra.clock
    key: ShowDayOfWeek
    type: int
    value: "{{ 1 if macos_menubar_clock_show_day_of_week else 0 }}"
    state: present
  notify: Restart SystemUIServer

- name: Use 24-hour clock
  community.general.osx_defaults:
    domain: com.apple.menuextra.clock
    key: Show24Hour
    type: int
    value: "{{ 1 if macos_menubar_clock_24hour else 0 }}"
    state: present
  notify: Restart SystemUIServer
