---
- name: Template tmux.conf
  ansible.builtin.template:
    src: tmux.conf.j2
    dest: "{{ ansible_facts['env']['HOME'] }}/.tmux.conf"
    mode: '0644'

- name: Ensure tmux plugin manager directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.tmux/plugins"
    state: directory
    mode: '0755'

- name: Clone tmux plugin manager (tpm)
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_facts['env']['HOME'] }}/.tmux/plugins/tpm"
    version: master
    update: true
